// <auto-generated />
using System;
using GeekNotes.Modules.Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekNotes.Modules.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20260701110637_Init_Identity")]
    partial class Init_Identity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("IDPModule")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeekNotes.Modules.Identity.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "IDPModule");
                });

            modelBuilder.Entity("GeekNotes.Modules.Identity.Domain.Roles.Role", b =>
                {
                    b.OwnsMany("GeekNotes.Modules.Identity.Domain.Roles.Permission", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .HasMaxLength(128)
                                .IsUnicode(false)
                                .HasColumnType("varchar(128)")
                                .HasColumnName("Permission");

                            b1.HasKey("RoleId", "Name");

                            b1.ToTable("RolePermissions", "IDPModule");

                            b1.WithOwner()
                                .HasForeignKey("RoleId");
                        });

                    b.OwnsOne("GeekNotes.Modules.Identity.Domain.Roles.RoleName", "Name", b1 =>
                        {
                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .IsUnicode(false)
                                .HasColumnType("varchar(64)")
                                .HasColumnName("Name");

                            b1.HasKey("RoleId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Roles", "IDPModule");

                            b1.WithOwner()
                                .HasForeignKey("RoleId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
